// generated from projects/poca-card/src/lib/v2/shaders/lygia/math.glsl
export default `#include <lygia/math/aamirror>
#include <lygia/math/absi>
#include <lygia/math/adaptiveThreshold>
#include <lygia/math/atan2>
#include <lygia/math/bump>
#include <lygia/math/const>
#include <lygia/math/cubic>
#include <lygia/math/decimate>
#include <lygia/math/dist>
#include <lygia/math/frac>
#include <lygia/math/gain>
#include <lygia/math/gaussian>
#include <lygia/math/grad4>
#include <lygia/math/highPass>
#include <lygia/math/inside>
#include <lygia/math/invCubic>
#include <lygia/math/inverse>
#include <lygia/math/invQuartic>
#include <lygia/math/lengthSq>
#include <lygia/math/lerp>
#include <lygia/math/map>
#include <lygia/math/mirror>
#include <lygia/math/mmax>
#include <lygia/math/mmin>
#include <lygia/math/mod2>
#include <lygia/math/mod289>
#include <lygia/math/nyquist>
#include <lygia/math/pack>
#include <lygia/math/parabola>
#include <lygia/math/permute>
#include <lygia/math/pow2>
#include <lygia/math/pow3>
#include <lygia/math/pow5>
#include <lygia/math/pow7>
#include <lygia/math/powFast>
#include <lygia/math/quartic>
#include <lygia/math/quat>
#include <lygia/math/quintic>
#include <lygia/math/rotate2d>
#include <lygia/math/rotate3d>
#include <lygia/math/rotate3dX>
#include <lygia/math/rotate3dY>
#include <lygia/math/rotate3dZ>
#include <lygia/math/rotate4d>
#include <lygia/math/rotate4dX>
#include <lygia/math/rotate4dY>
#include <lygia/math/rotate4dZ>
#include <lygia/math/round>
#include <lygia/math/saturate>
#include <lygia/math/saturateMediump>
#include <lygia/math/scale2d>
#include <lygia/math/scale3d>
#include <lygia/math/scale4d>
#include <lygia/math/select>
#include <lygia/math/smootherstep>
#include <lygia/math/sum>
#include <lygia/math/taylorInvSqrt>
#include <lygia/math/toMat4>
#include <lygia/math/translate4d>
#include <lygia/math/transpose>
#include <lygia/math/unpack>
#include <lygia/math/within>
`;
